#! /usr/bin/env python

def configure(conf):
    pass

def build(bld):
	bld.new_task_gen(
		features = 'cxx cshlib',
		source = 'engine.cc clientengine.cc transengine.cc controlapi.cc',
		target = 'jackserver',
		includes = ". .. ../config",
		lib = ['dl', 'pthread'] )

	bld.new_task_gen(
		features = 'cxx cprogram',
		source = 'jackd.cc',
		target = 'jackd',
		includes = ". .. ../config",
		uselib_local = [ "jackserver", "jack" ],
		lib = ['dl', 'pthread'] )

