#! /usr/bin/env python

def configure(conf):
    conf.sub_config('dummy')
    conf.sub_config('alsa')
#    conf.sub_config('netjack')
    conf.sub_config('firewire')

def build(bld):
    bld.add_subdirs('dummy')
    bld.add_subdirs('alsa')
#    bld.add_subdirs('netjack')
    bld.add_subdirs('firewire')
