#! /usr/bin/env python

def configure(conf):
    conf.check_cfg( package="gtkmm-2.4", args="--cflags --libs" )
    conf.check_cfg( package="jack", args="--cflags --libs" )

def build(bld):
	bld.new_task_gen(
		features = 'cxx cshlib',
		source = 'client.cc driver.cc intclient.cc messagebuffer.cc midiport.cc pool.cc port.cc ringbuffer.cc sanitycheck.cc shm.cc simd.cc systemtest.cc thread.cc time.cc timestamps.cc transclient.cc unlock.cc',
		target = 'jack',
		includes = ".. ../config",
		lib = ['dl', 'pthread', 'rt'] )



