#! /usr/bin/env python

def configure(conf):
    conf.check_cfg( package="gtkmm-2.4", args="--cflags --libs" )
    conf.check_cfg( package="jack", args="--cflags --libs" )

def build(bld):
	bld.new_task_gen(
		features = 'cxx cshlib',
		source = 'client.c driver.c intclient.c messagebuffer.c midiport.c pool.c port.c ringbuffer.c sanitycheck.c shm.c simd.c systemtest.c thread.c time.c timestamps.c transclient.c unlock.c',
		target = 'jack',
		includes = "../",
		lib = "dl pthread")



