#! /usr/bin/env python

def configure(conf):
    conf.check_cfg( package="alsa", args="--cflags --libs" )

def build(bld):
	driver = bld.new_task_gen(
		    features = 'cxx cshlib',
		    source = "alsa_driver.cc generic_hw.cc hammerfall.cc hdsp.cc ice1712.cc memops.cc usx2y.cc ../alsa-midi/alsa_rawmidi.cc ../alsa-midi/alsa_seqmidi.cc",
		    target = 'alsa',
		    includes = "../.. ../../config",
		    uselib = "ALSA",
		    lib = ['dl', 'pthread', 'rt'] )

	driver.env['shlib_PATTERN'] = 'jack_%s.so'


